# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9315666a0f4031821e6e6a23859fdc5a9a467b953332b9c71f966777113933b1d159c8374d0b7bf72fe29b7a8ab5162845cec0bc7da62800049f71c1eea77b

test:
  secret_key_base: c1bbc329633efa574769607071a554e1706ad697d50b537ac3f44b6930c1aaaf4aa37c979ba7f385a55946c7ac0b12e9ca717016f9e35ba47c543abc4360626b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
